version: '3.3'
services:
  mysqlsrv:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'abril'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin123'
#      MYSQL_ROOT_PASSWORD: '1234'
    ports:
      - '3310:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib
volumes:
  my-db: